// AUTO-GENERATED by #[rpc_command]. Do not edit.
import type { TestCmd } from '../../generated/TestCmd.ts';

type Variant = Extract<TestCmd, { type: 'OnlyAuto' }>;

export function onlyAuto(): TestCmd {
  return {
    type: 'OnlyAuto',
    at: new Date().toISOString(),
  };
}
