// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateSepaMandate = { id: bigint, customer_id: bigint, mandate_ref: string, iban: string, bic: string, holder_name: string, signed_at: string, };
