// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateRecurring = { id: bigint, customer_id: bigint, template_name: string, interval_unit: string, interval_value: bigint, next_run: string, status_template: string, notes_template: string, };
