// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateContact = { id: string, customer_id: string, name: string, email: string, phone: string, role: string, is_primary: bigint, };
