// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cascades recurring_positions + recurring_invoice atomically.
 * Also writes an activity_log row (action='delete', entity_type='recurring').
 */
export type DeleteRecurring = { id: string, activity_id: string, timestamp: string, label_for_detail: string, };
