// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LogActivity = { id: bigint, timestamp: string, entity_type: string, entity_id: bigint, action: string, actor: string, detail: string, };
