// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Creates a new invoice with positions copied from the recurring template.
 * `position_ids` must have as many entries as the template has positions.
 * Updates last_run + next_run on the recurring row.
 */
export type RunRecurringOnce = { recurring_id: string, new_invoice_id: string, position_ids: string[], new_number: string, issue_date: string, due_date: string, new_next_run: string, };
