// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A position embedded in the Storno credit note (pre-negated quantity,
 * pre-assigned ID). Idempotent: re-applying the command inserts the same rows.
 */
export type StornoPosition = { id: string, position_nr: number, description: string, quantity: number, unit_price: number, tax_rate: number, product_id: string | null, item_number: string, unit: string, discount_pct: number, cost_price: number, position_type: string, };
