// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateCustomer = { id: bigint, name: string, email: string, company_type: string, tax_id: string, vat_id: string, payment_terms_days: bigint, default_discount_pct: bigint, billing_street: string, billing_zip: string, billing_city: string, billing_country: string, shipping_street: string, shipping_zip: string, shipping_city: string, shipping_country: string, default_iban: string, default_bic: string, notes: string, };
