// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateProduct = { id: bigint, sku: string, name: string, description: string, unit: string, unit_price: bigint, tax_rate: bigint, cost_price: bigint, active: bigint, };
