// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdatePosition = { id: string, description: string, quantity: number, unit_price: number, tax_rate: number, product_id: string, item_number: string, unit: string, discount_pct: number, cost_price: number, position_type: string, };
