// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateProduct = { id: string, sku: string, name: string, description: string, unit: string, unit_price: number, tax_rate: number, cost_price: number, active: number, };
