// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateRecurringPosition = { id: bigint, description: string, quantity: bigint, unit_price: bigint, tax_rate: bigint, unit: string, item_number: string, discount_pct: bigint, };
