// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdatePosition = { id: string, description: string, quantity: bigint, unit_price: bigint, tax_rate: bigint, product_id: string, item_number: string, unit: string, discount_pct: bigint, cost_price: bigint, position_type: string, };
