//! Pure-render tests for `render_bundle`. No filesystem IO.

use rpc_command::{render_bundle, StructSpec};

#[test]
fn empty_bundle() {
    let out = render_bundle("MyCmd", &[]);
    let expected = "\
// AUTO-GENERATED by #[rpc_command_enum]. Do not edit.
import type { MyCmd } from './MyCmd.ts';
";
    assert_eq!(out, expected);
}

#[test]
fn single_command_no_defaults() {
    let spec = StructSpec {
        struct_name: "DeleteInvoice",
        fn_name: "deleteInvoice",
        inputs: &["id"],
        auto: &[],
    };
    let out = render_bundle("InvoiceCommand", &[spec]);
    let expected = "\
// AUTO-GENERATED by #[rpc_command_enum]. Do not edit.
import type { InvoiceCommand } from './InvoiceCommand.ts';

export function deleteInvoice(
  input: Omit<Extract<InvoiceCommand, { type: 'DeleteInvoice' }>, 'type'>,
): InvoiceCommand {
  return {
    type: 'DeleteInvoice',
    ...input,
  };
}
";
    assert_eq!(out, expected);
}

#[test]
fn single_command_with_two_auto_fields() {
    let spec = StructSpec {
        struct_name: "MarkPaid",
        fn_name: "markPaid",
        inputs: &["id"],
        auto: &[
            ("activity_id", "nextId()"),
            ("timestamp", "new Date().toISOString()"),
        ],
    };
    let out = render_bundle("InvoiceCommand", &[spec]);
    assert!(out.starts_with(
        "// AUTO-GENERATED by #[rpc_command_enum]. Do not edit.\n\
         import type { InvoiceCommand } from './InvoiceCommand.ts';\n\
         import { nextId } from '@wasmdb/client';\n"
    ));
    assert!(out.contains(
        "input: Omit<Extract<InvoiceCommand, { type: 'MarkPaid' }>, 'type' | 'activity_id' | 'timestamp'>"
    ));
    assert!(out.contains("activity_id: nextId(),"));
    assert!(out.contains("timestamp: new Date().toISOString(),"));
}

#[test]
fn multiple_commands_share_one_import_block() {
    let specs = [
        StructSpec {
            struct_name: "A",
            fn_name: "a",
            inputs: &["id"],
            auto: &[("activity_id", "nextId()")],
        },
        StructSpec {
            struct_name: "B",
            fn_name: "b",
            inputs: &["id"],
            auto: &[("activity_id", "nextId()")],
        },
    ];
    let out = render_bundle("Cmd", &specs);
    // nextId import appears exactly once, regardless of how many factories use it.
    assert_eq!(out.matches("import { nextId }").count(), 1);
    assert!(out.contains("export function a("));
    assert!(out.contains("export function b("));
}

#[test]
fn nested_struct_field_is_transparent() {
    let spec = StructSpec {
        struct_name: "Storno",
        fn_name: "storno",
        inputs: &["id", "positions"],
        auto: &[("activity_id", "nextId()")],
    };
    let out = render_bundle("InvoiceCommand", &[spec]);
    // Inputs flow through Omit<Extract<...>>, never naming Rust types.
    assert!(out.contains(
        "Omit<Extract<InvoiceCommand, { type: 'Storno' }>, 'type' | 'activity_id'>"
    ));
    assert!(!out.contains("Vec<"));
    assert!(!out.contains("Option<"));
    assert!(!out.contains("StornoPosition")); // imported by ts-rs, not by us
}

#[test]
fn no_next_id_means_no_wasm_import() {
    let spec = StructSpec {
        struct_name: "Plain",
        fn_name: "plain",
        inputs: &["x"],
        auto: &[("at", "new Date().toISOString()")],
    };
    let out = render_bundle("C", &[spec]);
    assert!(!out.contains("nextId"));
    assert!(!out.contains("wasm.ts"));
}

#[test]
fn auto_only_command_has_zero_arg_factory() {
    let spec = StructSpec {
        struct_name: "Heartbeat",
        fn_name: "heartbeat",
        inputs: &[],
        auto: &[("ts", "new Date().toISOString()")],
    };
    let out = render_bundle("C", &[spec]);
    assert!(out.contains("export function heartbeat(): C {"));
    assert!(!out.contains("...input"));
    assert!(out.contains("ts: new Date().toISOString(),"));
}

#[test]
fn omit_clause_preserves_auto_field_order() {
    let spec = StructSpec {
        struct_name: "X",
        fn_name: "x",
        inputs: &["i"],
        auto: &[("a", "1"), ("b", "2"), ("c", "3")],
    };
    let out = render_bundle("C", &[spec]);
    assert!(out.contains("'type' | 'a' | 'b' | 'c'"));
}
