// AUTO-GENERATED by #[rpc_command]. Do not edit.
import type { TestCmd } from '../../generated/TestCmd.ts';
import { nextId } from '../../wasm.ts';

type Variant = Extract<TestCmd, { type: 'WithNested' }>;

export function withNested(
  input: Omit<Variant, 'type' | 'activity_id' | 'timestamp'>,
): TestCmd {
  return {
    type: 'WithNested',
    activity_id: nextId(),
    timestamp: new Date().toISOString(),
    ...input,
  };
}
