// AUTO-GENERATED by #[rpc_command]. Do not edit.
import type { TestCmd } from '../generated/TestCmd.ts';

type Variant = Extract<TestCmd, { type: 'Flat' }>;

export function flat(
  input: Omit<Variant, 'type'>,
): TestCmd {
  return {
    type: 'Flat',
    ...input,
  };
}
