//! Runtime helpers for `#[rpc_command]` / `#[rpc_command_enum]`.
//!
//! Two macros, two responsibilities:
//!
//! * `#[rpc_command]` — applied to a command struct. Adds the standard derive
//!   bundle and emits a `pub const __RPC_COMMAND_SPEC: StructSpec<'static>`
//!   that the enum-level macro consumes.
//! * `#[rpc_command_enum]` — applied to the wire-format enum. Walks the
//!   variants and, on `cargo test`, writes a single bundled
//!   `<EnumName>Factories.ts` next to the ts-rs output.
//!
//! Per-variant escape hatch: `#[rpc_command_skip]` excludes a variant from
//! the bundle (used during incremental migration when not every variant has
//! a `#[rpc_command]` spec yet).

pub use rpc_command_derive::{rpc_command, rpc_command_enum};

/// One auto-filled field of a command: the field name (snake_case, as in
/// Rust/TS) and the TS expression that produces its value at call time
/// (e.g. `nextId()`).
pub type AutoField<'a> = (&'a str, &'a str);

/// Per-command metadata. The `#[rpc_command]` macro emits one of these as a
/// `const` on the struct; the enum macro reads them at test-time.
#[derive(Debug, Clone, Copy)]
pub struct StructSpec<'a> {
    /// Rust struct name; also the wire-format discriminator.
    pub struct_name: &'a str,
    /// camelCase TS factory function name.
    pub fn_name: &'a str,
    /// Caller-supplied fields → appear in the factory's `input` parameter.
    pub inputs: &'a [&'a str],
    /// Auto-filled fields → `(field_name, ts_expression)`.
    pub auto: &'a [AutoField<'a>],
}

/// Render the bundled factory file for an enum.
///
/// Pure function: no IO. Tested directly by `tests/render.rs`.
pub fn render_bundle(enum_name: &str, specs: &[StructSpec<'_>]) -> String {
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by #[rpc_command_enum]. Do not edit.\n");
    out.push_str(&format!(
        "import type {{ {enum_name} }} from './{enum_name}.ts';\n"
    ));

    if specs.iter().any(|s| s.auto.iter().any(|(_, e)| e.contains("nextId("))) {
        out.push_str("import { nextId } from '@wasmdb/client';\n");
    }

    for spec in specs {
        out.push('\n');
        write_factory(&mut out, enum_name, spec);
    }
    out
}

fn write_factory(out: &mut String, enum_name: &str, spec: &StructSpec<'_>) {
    let mut omit = vec![String::from("'type'")];
    omit.extend(spec.auto.iter().map(|(n, _)| format!("'{n}'")));
    let omit_clause = omit.join(" | ");
    let extract = format!(
        "Extract<{enum_name}, {{ type: '{struct_name}' }}>",
        struct_name = spec.struct_name,
    );

    if spec.inputs.is_empty() && spec.auto.is_empty() {
        out.push_str(&format!(
            "export function {fn_name}(): {enum_name} {{\n  return {{ type: '{struct_name}' }} as {enum_name};\n}}\n",
            fn_name = spec.fn_name,
            enum_name = enum_name,
            struct_name = spec.struct_name,
        ));
        return;
    }

    if spec.inputs.is_empty() {
        out.push_str(&format!(
            "export function {fn_name}(): {enum_name} {{\n",
            fn_name = spec.fn_name,
        ));
    } else {
        out.push_str(&format!(
            "export function {fn_name}(\n  input: Omit<{extract}, {omit_clause}>,\n): {enum_name} {{\n",
            fn_name = spec.fn_name,
        ));
    }
    out.push_str("  return {\n");
    out.push_str(&format!("    type: '{}',\n", spec.struct_name));
    for (n, e) in spec.auto {
        out.push_str(&format!("    {n}: {e},\n"));
    }
    if !spec.inputs.is_empty() {
        out.push_str("    ...input,\n");
    }
    out.push_str("  };\n");
    out.push_str("}\n");
}

/// Write the bundle file. Resolution of the output directory:
/// 1. `RPC_COMMAND_TS_ROOT` env var (set by the consuming crate's build.rs;
///    invoice-demo points at `frontend/packages/generated/src`).
/// 2. `<CARGO_MANIFEST_DIR>/../../frontend/packages/generated/src/` (legacy
///    fallback if no env var is set).
///
/// `bundle_name` is the filename (sans `.ts`); `enum_name` is the wire-format
/// enum referenced inside the file (`import type { EnumName }` + `Extract<...>`).
pub fn export_bundle_named(bundle_name: &str, specs: &[StructSpec<'_>], enum_name: &str) {
    let body = render_bundle(enum_name, specs);
    let root = ts_root();
    let full_path = format!("{root}/{bundle_name}.ts");
    if let Some(parent) = std::path::Path::new(&full_path).parent() {
        std::fs::create_dir_all(parent).expect("create_dir_all");
    }
    std::fs::write(&full_path, &body).unwrap_or_else(|e| {
        panic!("rpc-command: failed to write {full_path}: {e}");
    });
    eprintln!("rpc-command: wrote {full_path}");
}

fn ts_root() -> String {
    if let Ok(v) = std::env::var("RPC_COMMAND_TS_ROOT") {
        return v;
    }
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")
        .expect("CARGO_MANIFEST_DIR — rpc-command runs under cargo");
    format!("{manifest_dir}/../../frontend/packages/generated/src")
}
