//! Client-side facade for invoice-demo tables.
//!
//! Row structs, fetcher markers, `fetch` call wrappers, and
//! `#[wasm_bindgen]` entry points are generated by `tables-codegen` in
//! `build.rs` from the sibling `tables-storage` crate's `#[row]` /
//! `#[query]` declarations.

pub use tables_client::FetchError;

/// URL of the invoice-demo server's table-fetch endpoint.
pub const TABLE_FETCH_URL: &str = "/table-fetch";

mod __generated {
    include!(concat!(env!("OUT_DIR"), "/generated.rs"));
}

pub use __generated::*;
